// src/products.js
export const products = [
  {
    id: 1,
    name: "Nike Run Defy",
    price: 12000,
    description: "Comfortable and stylish shoes for daily wear.",
    images: ["/MY-Project/shoes1.jpg", "/MY-Project/shoes1-1.jpg", "/MY-Project/shoes1-2.jpg", "/MY-Project/shoes1-3.jpg"],
  },
  {
    id: 2,
    name: "Nike Zoom Rival Fly 4",
    price: 12000,
    description: "High-performance running shoes with modern design.",
    images: ["/MY-Project/shoes2.jpg", "/MY-Project/shoes2-1.jpg", "/MY-Project/shoes2-2.jpg", "/MY-Project/shoes2-3.jpg"],
  },
  {
    id: 3,
    name: "Nike Run Swift 3",
    price: 14000,
    description: "Premium quality UB 5 shoes for running and training.",
    images: ["/MY-Project/shoes11.jpg", "/MY-Project/shoes11.1.jpg","/MY-Project/shoes11.2.jpg", "/MY-Project/shoes11.3.jpg"],
  },
  {
    id: 4,
    name: "Nike Vomero 18 GORE-TEX",
    price: 16000,
    description: "Lightweight and responsive shoes for speed runners.",
    images: ["/MY-Project/shoes12.jpg", "/MY-Project/shoes12-1.jpg","/MY-Project/shoes12-2.jpg", "/MY-Project/shoes12-3.jpg"],
  },
  {
    id: 5,
    name: "Nike Ultrafly",
    price: 15000,
    description: "Elite racing shoes with carbon plate technology.",
    images: ["/MY-Project/shoes13.jpg", "/MY-Project/shoes13-1.jpg","/MY-Project/shoes13.2.jpg","/MY-Project/shoes13-3.jpg"],
  },
  {
    id: 6,
    name: "Nike Vomero Premium",
    price: 13000,
    description: "Breathable and stylish white running shoes.",
    images: ["/MY-Project/shoes14.jpg", "/MY-Project/shoes14-1.jpg","/MY-Project/shoes14-2.jpg","/MY-Project/shoes14.3.jpg"],
  },
  {
    id: 7,
    name: "Nike Vomero 18",
    price: 13000,
    description: "Durable winter tech shoes with excellent grip.",
    images: ["/MY-Project/shoes15.jpg", "/MY-Project/shoes15-1.jpg","/MY-Project/shoes15-2.jpg", "/MY-Project/shoes15-3.jpg"],
  },
  {
    id: 8,
    name: "Nike Motiva",
    price: 19000,
    description: "New Balance Fresh Foam X with premium comfort.",
    images: ["/MY-Project/shoes16.jpg", "/MY-Project/shoes16-1.jpg","/MY-Project/shoes16-2.jpg","/MY-Project/shoes16-3.jpg"],
  },
  {
    id: 9,
    name: "Nike Pegasus 41",
    price: 10000,
    description: "Classic AM 720 shoes with cushioned support.",
    images: ["/MY-Project/shoes17.jpg", "/MY-Project/shoes17-1.jpg","/MY-Project/shoes17-2.jpg","/MY-Project/shoes17-3.jpg",],
  },
  {
    id: 10,
    name: "Nike Zoom Rival Sprint",
    price: 15000,
    description: "Stylish all-black design with Fresh Foam comfort.",
    images: ["/MY-Project/shoes18.jpg", "/MY-Project/shoes18-1.jpg","/MY-Project/shoes18-2.jpg","/MY-Project/shoes18-3.jpg"],
  },
  {
    id: 11,
    name: "Nike Run Defy",
    price: 12000,
    description: "Premium Dunk Low sneakers with venom theme.",
    images: ["/MY-Project/shoes19.jpg", "/MY-Project/shoes19-1.jpg","/MY-Project/shoes19-2.jpg","/MY-Project/shoes19-3.jpg"],
  },
  {
    id: 12,
    name: "Nike Vomero Plus",
    price: 12000,
    description: "Air Jordan IV Fear edition with iconic style.",
    images: ["/MY-Project/shoes20.jpg", "/MY-Project/shoes20-1.jpg","/MY-Project/shoes20-2.jpg","/MY-Project/shoes20-3.jpg",],
  },
];
